/**
 * DCF × OpenClaw 统一错误码。
 * DCF 端和 Runtime 端必须使用相同的错误码字符串。
 */
const RuntimeErrorCodes = Object.freeze({
  // 契约层
  CONTRACT_VERSION_MISMATCH: 'CONTRACT_VERSION_MISMATCH',
  INVALID_RUNTIME_SUBMIT: 'INVALID_RUNTIME_SUBMIT',

  // 查询层
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',

  // 校验层
  INVALID_RUNTIME_STATUS: 'INVALID_RUNTIME_STATUS',
  INVALID_RUNTIME_EVENT: 'INVALID_RUNTIME_EVENT',

  // 执行层（Runtime 端产出，DCF 端消费）
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  TASK_TIMEOUT: 'TASK_TIMEOUT',

  // 可用性
  RUNTIME_UNAVAILABLE: 'RUNTIME_UNAVAILABLE',
  RUNTIME_TASK_ID_MISSING: 'RUNTIME_TASK_ID_MISSING',

  // 中止层（DCF Gateway 产出）
  ABORT_FAILED: 'ABORT_FAILED',
  ABORT_TIMEOUT: 'ABORT_TIMEOUT',
  ABORT_NOT_FOUND: 'ABORT_NOT_FOUND',
  ABORT_REJECTED: 'ABORT_REJECTED',
  ABORT_POLICY_DENIED: 'RUNTIME_ABORT_POLICY_DENIED'
});

module.exports = { RuntimeErrorCodes };

