const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

test('admin skills detail drawer renders content-first view and keeps raw json expansion state', () => {
  const file = path.resolve(__dirname, '..', 'public/admin/skills.js');
  const htmlFile = path.resolve(__dirname, '..', 'public/admin/skills.html');
  const js = fs.readFileSync(file, 'utf8');
  const html = fs.readFileSync(htmlFile, 'utf8');
  assert.equal(js.includes('SKILL.md（全量）'), true);
  assert.equal(js.includes('renderMarkdownDocument'), true);
  assert.equal(js.includes('资源声明'), true);
  assert.equal(js.includes('data-skill-resource-path'), true);
  assert.equal(js.includes('selectedResourcePathBySkillId'), true);
  assert.equal(js.includes('关联员工'), true);
  assert.equal(js.includes('运行态真实返回（Runtime Truth）'), true);
  assert.equal(js.includes('runtimeMeta.platformInference'), true);
  assert.equal(js.includes('平台推断字段'), true);
  assert.equal(js.includes('运行态原始字段'), true);
  assert.equal(js.includes('管理信息（可选）'), true);
  assert.equal(js.includes('风险分'), false);
  assert.equal(js.includes('${renderStructuredDefinition(structure, detail)}'), false);
  assert.equal(js.includes('rawJsonExpandedBySkillId'), true);
  assert.equal(js.includes('managerInfoExpandedBySkillId'), true);
  assert.equal(js.includes('admin.skills.debug'), true);
  assert.equal(js.includes('admin.skills.action.debug-toggle'), true);
  assert.equal(js.includes('debugToggleBtn'), false);
  assert.equal(js.includes('skillRawJsonDetails'), true);
  assert.equal(js.includes('skillManagerDetails'), true);
  assert.equal(js.includes('currentDetailDigest'), true);
  assert.equal(js.includes('nextDetailDigest === currentDetailDigest'), true);
  assert.equal(js.includes("addEventListener('toggle'"), true);
  assert.equal(js.includes('admin.skills.delete'), true);
  assert.equal(js.includes('admin.skills.action.unlink-employee'), true);
  assert.equal(js.includes('admin.skills.action.delete'), true);
  assert.equal(html.includes('id="debugToggleBtn"'), false);
  assert.equal(js.includes('data-delete-skill-id'), true);
  assert.equal(js.includes('data-unlink-employee-id'), true);
  assert.equal(js.includes('data-link-employee-btn'), true);
  assert.equal(js.includes('data-required-permission="admin.skills.write"'), true);
  assert.equal(js.includes('data-required-permission="admin.skills.action.unlink-employee"'), true);
  assert.equal(js.includes('data-required-permission="admin.skills.action.delete"'), true);
  assert.equal(js.includes('applyActionAcl(body);'), true);
  assert.equal(js.includes('applyActionAcl(document);'), true);
  assert.equal(js.includes('当前账号没有运行策略写入权限（admin.runtime.write）'), true);
  assert.equal(js.includes('当前账号没有技能写入权限（admin.skills.write）'), true);
  assert.equal(js.includes('class="admin-select" data-link-employee-select'), true);
  assert.equal(js.includes('/api/admin/skills/employees'), true);
  assert.equal(js.includes('/link'), true);
  assert.equal(js.includes('formatSkillSourceLabel'), true);
  assert.equal(js.includes('预置技能'), true);
  assert.equal(js.includes('压缩包导入'), true);
  assert.equal(js.includes('filterSkillEmployee'), true);
  assert.equal(js.includes('employeeId'), true);
  assert.equal(js.includes('请输入员工ID进行二次确认'), true);
  assert.equal(js.includes('二次确认未通过，已取消解除关联'), true);
  assert.equal(js.includes('window.prompt'), true);
  assert.equal(js.includes('/api/admin/runtime/skill-sedimentation-policy'), true);
  assert.equal(js.includes('setSkillPolicyDrawerVisibility'), true);
  assert.equal(js.includes('openSkillPolicyDrawerBtn'), true);
  assert.equal(js.includes('skillPolicyDrawerMask'), true);
  assert.equal(js.includes('saveSkillPolicyBtn'), true);
  assert.equal(js.includes('skillPolicyModeSelect'), true);
  assert.equal(js.includes('applySkillPolicyModeSpecificFieldState'), true);
  assert.equal(js.includes('renderSkillPolicyRuleConfigSummary'), true);
  assert.equal(js.includes('renderSkillPolicyOverridesEditor'), true);
  assert.equal(js.includes('validateSkillPolicyOverrides'), true);
  assert.equal(js.includes('createSkillPolicyOverrideTemplate'), false);
  assert.equal(js.includes('renderSkillPolicyEffectivePreview'), true);
  assert.equal(js.includes('skillPolicyToastTimer'), true);
  assert.equal(js.includes("document.getElementById('skillPolicyToast')"), true);
  assert.equal(js.includes('覆盖规则生效数：'), true);
  assert.equal(js.includes('data-override-field'), true);
  assert.equal(js.includes('data-override-scope-field'), true);
  assert.equal(js.includes('buildSkillPolicyOverridesPayload'), true);
  assert.equal(js.includes('系统固定规则：同类任务只有“成功”才会累计次数。'), true);
  assert.equal(html.includes('id="openSkillPolicyDrawerBtn" type="button">技能沉淀策略</button>'), true);
  assert.equal(html.includes('id="skillPolicyDrawer" class="employee-drawer skill-detail-drawer hidden"'), true);
  assert.equal(html.includes('id="skillPolicyRulesSection" class="skill-detail-card"'), true);
  assert.equal(html.includes('id="skillPolicyPreviewSection" class="skill-detail-card"'), true);
  assert.equal(html.includes('id="skillPolicyEffectivePreview" class="toolbar-note"'), true);
  assert.equal(html.includes('id="skillPolicyRuleSummary" class="toolbar-note"'), true);
  assert.equal(html.includes('id="skillPolicyRuleList" class="section-note skill-policy-rule-list"'), true);
  assert.equal(html.includes('id="addSkillPolicyOverrideBtn" type="button">新增覆盖规则</button>'), true);
  assert.equal(html.includes('data-override-template='), false);
  assert.equal(html.includes('id="skillPolicyOverridesList"'), true);
  assert.equal(html.includes('class="employee-drawer-body skill-policy-body"'), true);
  assert.equal(html.includes('class="skill-policy-overrides-head"'), true);
  assert.equal(html.includes('高级模式：查看 JSON（可选）'), true);
  assert.equal(html.includes('id="closeSkillPolicyDrawer" type="button">关闭</button>'), true);
  assert.equal(html.includes('id="skillPolicyDrawerMask" class="employee-drawer-mask hidden"'), true);
  assert.equal(html.includes('id="filterSkillSource"'), true);
  assert.equal(html.includes('id="filterSkillName"'), true);
  assert.equal(html.includes('id="filterSkillEmployee"'), true);
  assert.equal(html.includes('id="skillPolicyModeSelect"'), true);
  assert.equal(html.includes('id="saveSkillPolicyBtn"'), true);
  assert.equal(html.includes('id="saveSkillPolicyBtn" type="button" data-required-permission="admin.runtime.write"'), true);
  assert.equal(html.includes('id="skillPolicyStatus"'), false);
  assert.equal(html.includes('id="skillPolicyToast" class="admin-toast hidden"'), true);
  assert.equal(html.includes('id="exportBtn" data-required-permission="admin.skills.read"'), true);
  assert.equal(html.includes('id="importBtn" class="primary" data-required-permission="admin.skills.write"'), true);
  assert.equal(html.includes('id="skillPolicyOverridesJson"'), true);
  assert.equal(html.includes('id="filterSearchBtn"'), false);
  assert.equal(html.includes('id="filterResetBtn"'), false);
  assert.equal(html.includes('class="toolbar filter-toolbar"'), true);
  assert.equal(html.includes('class="admin-select" id="filterSkillSource"'), true);
  assert.equal(html.includes('class="admin-input" id="filterSkillName"'), true);
  assert.equal(html.includes('class="employee-drawer skill-detail-drawer hidden"'), true);
  assert.equal(html.includes('全部来源'), true);
});
