const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

test('auth users page supports user drawer workflows', () => {
  const htmlFile = path.resolve(__dirname, '..', 'public/admin/auth-users.html');
  const jsFile = path.resolve(__dirname, '..', 'public/admin/auth-members.js');
  const html = fs.readFileSync(htmlFile, 'utf8');
  const js = fs.readFileSync(jsFile, 'utf8');

  assert.equal(html.includes('id="openCreateUserDrawerBtn"'), true);
  assert.equal(html.includes('id="openCreateUserDrawerBtn" type="button" class="primary" data-required-permission="admin.auth.write"'), true);
  assert.equal(html.includes('授权用户'), false);
  assert.equal(html.includes('<h3>用户</h3>'), false);
  assert.equal(html.includes('<h3>用户列表</h3>'), false);
  assert.equal(html.includes('id="authTabUsers"'), false);
  assert.equal(html.includes('操作列支持编辑授权角色与删除授权用户（含二次确认）。'), false);
  assert.equal(html.includes('id="createUserDrawerMask"'), true);
  assert.equal(html.includes('id="createUserDrawer"'), true);
  assert.equal(html.includes('id="newUsername" type="text" readonly disabled'), true);
  assert.equal(html.includes('系统自动生成，无需填写'), true);
  assert.equal(html.includes('id="userEditDrawerMask"'), true);
  assert.equal(html.includes('id="userEditDrawer"'), true);
  assert.equal(html.includes('id="saveUserEditBtn"'), true);
  assert.equal(html.includes('id="saveUserEditBtn" type="button" class="primary" data-required-permission="admin.auth.write"'), true);
  assert.equal(html.includes('id="userDeleteConfirmModal"'), true);
  assert.equal(html.includes('id="confirmUserDeleteBtn"'), true);
  assert.equal(html.includes('id="confirmUserDeleteBtn" type="button" class="primary" data-required-permission="admin.auth.write"'), true);
  assert.equal(html.includes('id="cancelCreateUserDrawerBtn"'), true);
  assert.equal(html.includes('id="closeCreateUserDrawerBtn"'), true);
  assert.equal(html.includes('id="authToast"'), true);
  assert.equal(js.includes('toggleCreateUserDrawer'), true);
  assert.equal(js.includes('closeCreateUserDrawer'), true);
  assert.equal(js.includes('toggleUserEditDrawer'), true);
  assert.equal(js.includes('openUserEditPanel'), true);
  assert.equal(js.includes('openDeleteUserConfirm'), true);
  assert.equal(js.includes('deleteUser('), true);
  assert.equal(js.includes('createUserDrawerMask'), true);
  assert.equal(js.includes('showToast'), true);
  assert.equal(js.includes('generateAutoUsername'), true);
  assert.equal(js.includes('validateCreateUserForm'), true);
  assert.equal(js.includes('data-required-permission="admin.auth.write"'), true);
  assert.equal(js.includes('window.adminApplyActionAclForRoot'), true);
});

test('auth roles page supports role creation drawer interaction', () => {
  const htmlFile = path.resolve(__dirname, '..', 'public/admin/auth-roles.html');
  const jsFile = path.resolve(__dirname, '..', 'public/admin/auth-roles.js');
  const cssFile = path.resolve(__dirname, '..', 'public/admin/layout.css');
  const html = fs.readFileSync(htmlFile, 'utf8');
  const js = fs.readFileSync(jsFile, 'utf8');
  const css = fs.readFileSync(cssFile, 'utf8');

  assert.equal(html.includes('权限目录（示例）'), false);
  assert.equal(html.includes('<h3>角色列表</h3>'), false);
  assert.equal(html.includes('id="openCreateRoleDrawerBtn"'), true);
  assert.equal(html.includes('id="downloadPermissionMatrixBtn"'), false);
  assert.equal(html.includes('id="openCreateRoleDrawerBtn" type="button" class="primary" data-required-permission="admin.auth.write"'), true);
  assert.equal(html.includes('id="exportModuleFilter"'), false);
  assert.equal(html.includes('id="exportActionRiskFilter"'), false);
  assert.equal(html.includes('id="roleCreateDrawerMask"'), true);
  assert.equal(html.includes('id="roleCreateDrawer"'), true);
  assert.equal(html.includes('id="roleCreateDrawer" class="role-create-drawer role-permission-drawer hidden"'), true);
  assert.equal(html.includes('id="createRolePermissionList"'), true);
  assert.equal(html.includes('id="roleEditDrawer"'), true);
  assert.equal(html.includes('id="roleEditDrawer" class="role-create-drawer role-permission-drawer hidden"'), true);
  assert.equal(html.includes('id="editRolePermissionList"'), true);
  assert.equal(html.includes('id="cancelCreateRoleDrawerBtn"'), true);
  assert.equal(html.includes('id="closeCreateRoleDrawerBtn"'), true);
  assert.equal(html.includes('id="createRoleBtn"'), true);
  assert.equal(js.includes('toggleRoleCreateDrawer'), true);
  assert.equal(js.includes('downloadPermissionMatrix'), false);
  assert.equal(js.includes('permission-matrix-export?'), false);
  assert.equal(js.includes('exportModuleFilter'), false);
  assert.equal(js.includes('exportActionRiskFilter'), false);
  assert.equal(js.includes('data-required-permission="admin.auth.write"'), true);
  assert.equal(js.includes('closeRoleCreateDrawer'), true);
  assert.equal(js.includes('toggleRoleEditDrawer'), true);
  assert.equal(js.includes('renderPermissionMatrix'), true);
  assert.equal(js.includes('resolveApiFeatureLabel'), true);
  assert.equal(js.includes('resolveApiFeatureByPath'), true);
  assert.equal(js.includes('resolvePageFunctionLabel'), true);
  assert.equal(js.includes('功能：</strong>'), true);
  assert.equal(js.includes('接口：</strong>'), false);
  assert.equal(js.includes('不直接对应页面（接口/动作权限）'), true);
  assert.equal(js.includes('不包含按钮级权限'), true);
  assert.equal(js.includes('按钮：</strong>'), true);
  assert.equal(js.includes('roleCreateDrawerMask'), true);
  assert.equal(css.includes('.role-permission-drawer .role-create-drawer-body'), true);
  assert.equal(css.includes('.role-permission-drawer .permission-matrix'), true);
});
