const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

test('employees page does not expose retrieval policy governance controls', () => {
  const htmlFile = path.resolve(__dirname, '..', 'public/admin/employees.html');
  const jsFile = path.resolve(__dirname, '..', 'public/admin/employees.js');
  const cssFile = path.resolve(__dirname, '..', 'public/admin/layout.css');
  const html = fs.readFileSync(htmlFile, 'utf8');
  const js = fs.readFileSync(jsFile, 'utf8');
  const css = fs.readFileSync(cssFile, 'utf8');

  assert.equal(html.includes('id="editRetrievalMode"'), false);
  assert.equal(html.includes('id="applyBatchRetrievalPolicy"'), false);
  assert.equal(html.includes('id="rollbackBatchRetrievalPolicy"'), false);
  assert.equal(html.includes('id="batchPolicyResult"'), false);
  assert.equal(html.includes('id="employeeKeyword"'), true);
  assert.equal(html.includes('class="admin-input" id="employeeKeyword"'), true);
  assert.equal(html.includes('id="departmentFilter"'), true);
  assert.equal(html.includes('id="roleFilter"'), true);
  assert.equal(html.includes('L1（低风险，自动放行）'), true);
  assert.equal(html.includes('L2（一般风险，自动放行）'), true);
  assert.equal(html.includes('L3（较高风险，自动放行）'), true);
  assert.equal(html.includes('L4（敏感风险，需审批）'), true);
  assert.equal(html.includes('L1-L3 自动放行（0 审批），L4 为敏感风险（默认 2 人审批且角色互异）'), true);
  assert.equal(html.includes('id="applyEmployeeFilters"'), false);
  assert.equal(html.includes('id="resetEmployeeFilters"'), false);
  assert.equal(html.includes('id="runBoundaryCheck"'), false);
  assert.equal(html.includes('id="editRuntimeSessionKey"'), false);
  assert.equal(html.includes('Session Key'), false);
  assert.equal(html.includes('id="optimizePolicyForLlm"'), true);
  assert.equal(html.includes('id="optimizePolicyForLlm" type="button" data-required-permission="admin.employees.write"'), true);
  assert.equal(html.includes('id="jobPolicyNarrative"'), true);
  assert.equal(html.includes('id="jobAllowValidation"'), true);
  assert.equal(html.includes('id="jobNarrativeValidation"'), true);
  assert.equal(js.includes('buildEmployeesQuery()'), true);
  assert.equal(js.includes('readEmployeeFilters()'), true);
  assert.equal(js.includes('function resolveRuntimeProfile(detail = {})'), true);
  assert.equal(js.includes('function canWriteEmployees()'), true);
  assert.equal(js.includes('editRuntimeSessionKey'), false);
  assert.equal(js.includes('runtimeProfile.sessionKey'), false);
  assert.equal(js.includes('runtimeProfile: {'), true);
  assert.equal(js.includes('openclawProfile: {'), false);
  assert.equal(js.includes('runBoundaryCheck'), false);
  assert.equal(js.includes('optimizePolicyPromptFromForm'), true);
  assert.equal(js.includes('hasAnyPolicyInput('), true);
  assert.equal(js.includes('showPolicyRequiredValidationHints'), true);
  assert.equal(js.includes('hidePolicyRequiredValidationHints'), true);
  assert.equal(js.includes('请至少填写一项边界信息或补充说明后再执行优化。'), true);
  assert.equal(js.includes('/policy-optimize'), true);
  assert.equal(js.includes('formatDepartmentLabel'), true);
  assert.equal(js.includes('DEPARTMENT_LABELS'), true);
  assert.equal(js.includes('formatRoleLabel'), true);
  assert.equal(js.includes('ROLE_LABELS'), true);
  assert.equal(js.includes('function formatDeptRoleText(department, role)'), true);
  assert.equal(js.includes('escapeHtml(formatDeptRoleText(employee.department, employee.role))'), true);
  assert.equal(js.includes("escapeHtml(formatDepartmentLabel(e.department) || '-')"), true);
  assert.equal(js.includes("escapeHtml(formatRoleLabel(e.role) || '-')"), true);
  assert.equal(js.includes('updateFilterOptions('), true);
  assert.equal(js.includes('职责范围 ${contract.allowCount} / 禁止边界 ${contract.denyCount}'), true);
  assert.equal(js.includes('data-required-permission="admin.employees.write"'), true);
  assert.equal(js.includes('function syncApprovalRowState(level)'), true);
  assert.equal(js.includes('rolesNode.placeholder = disabled ? \'0 审批时不生效\''), true);
  assert.equal(js.includes('syncApprovalFormState();'), true);
  assert.equal(js.includes('/api/admin/employees${buildEmployeesQuery()}'), true);
  assert.equal(js.includes('/api/admin/employees/retrieval-policy/rollout'), false);
  assert.equal(js.includes('/api/admin/employees/retrieval-policy/rollback'), false);
  assert.equal(css.includes('.employee-drawer-body,\n.employee-drawer-editor'), true);
  assert.equal(css.includes('.employee-drawer .detail-section h4,'), true);
  assert.equal(css.includes('.employee-drawer .policy-grid label,'), true);
  assert.equal(css.includes('.employee-drawer pre {'), true);
  assert.equal(css.includes('#employeeDetailDrawer,\n#employeeDetailDrawer .employee-drawer-body,\n#employeeDetailDrawer .employee-drawer-editor'), true);
  assert.equal(css.includes('#employeeDetailDrawer .detail-section h4,'), true);
  assert.equal(css.includes('#employeeDetailDrawer .toolbar-note,'), true);
  assert.equal(css.includes('.policy-inline-validation {'), true);
});
